### ISSUE TITLE
WebApi cs-username IIS logging

### ISSUE THREAD

**Issue by 1Jesper1** [CrescentFresh/AccessTokenValidationIISLogging#1]
Hello, dit you manage to get this working for WebApi projects?
It only works for MVC projects.
I saw your issue at: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/76
It should work with version _2.14.0_ right?

Do I need this: `JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();`?

**Comment by CrescentFresh** [comment]
username is being logged to IIS logs in WebApi projects, yes. It was fixed in version 2.14.0, correct.

I don't believe that line of code is necessary but I could be wrong.

**Comment by 1Jesper1** [comment]
I was missing the name claim.

**Comment by 1Jesper1** [comment]
Hello @CrescentFresh Do you also know how to use this in .NET Core with [https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation)?
I saw this comment: [https://github.com/IdentityServer/IdentityServer4/issues/372#issuecomment-253358518](https://github.com/IdentityServer/IdentityServer4/issues/372#issuecomment-253358518)


Update: I think ` x.JwtBearerEvents = new JwtBearerEvents()
                    {
                         OnTokenValidated = ctx =>`
